import Head from "next/head";
import styles from "../../../styles/Home.module.css";
import Cell from "../../../componants/Cell";
import Navbar from "../../../componants/Navbar";
import CenteredContainer from "../../../componants/CenteredContainer";
import { useEffect, useState } from "react";
import {ScrereRecording} from "../../../componants/ScreneRecording";

export default function Home() {
    const [isTeacher, setIsTeacher] = useState(false);

    useEffect(() => {
        const user = JSON.parse(localStorage.getItem("user"));
        if (user) {
            if (user.isLoggedIn === undefined || user.isLoggedIn === false) {
                router.push("/auth");
            }
            if (user.role === "teacher") {
                setIsTeacher(true);
            }
        } else {
            router.push("/auth");
        }
        
    }, []);

    return (
        <div className={styles.container}>
            <Head>
                <title>LabTastic</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <Navbar />
            
            <div  style={{
                margin:"250px"
            }}>
            
            {isTeacher && <ScrereRecording></ScrereRecording>}

            <CenteredContainer >
                <Cell />
            </CenteredContainer>
            </div>
        </div>
    );
}