import Head from "next/head";
import styles from "../../../styles/Home.module.css";
import Cell from "../../../componants/Cell";
import Navbar from "../../../componants/Navbar";
import CenteredContainer from "../../../componants/CenteredContainer";
export default function Home() {

    return (
        <div className={styles.container}>
            <Head>
                <title>LabTastic</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <Navbar />
            
            <div  style={{
                margin:"250px"
            }}>
            <CenteredContainer >
                <Cell />
            </CenteredContainer>
            </div>
        </div>
    );
}