import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>LabTastic</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <p>Lab Tastic</p>
      </main>
    </div>
  );
}
