import Head from "next/head";
import Navbar from "../../componants/Navbar";
import { Button, Text } from "@mantine/core";
import NewCourseModal from "../../componants/NewCourseModal";
import { useEffect, useState } from "react";
import axios from "axios";
import { useRouter } from "next/router";
import CodeModal from "../../componants/CodeModal";
import LabSelectModal from "../../componants/LabSelectModal";
export default function Home(props) {
  const router = useRouter();
  const { id } = router.query;
  const [isTeacher, setIsTeacher] = useState(false);
  const [codeModal, setCodeModal] = useState(false);
  const [labDemo, setLabDemo] = useState(false);
  const [course, setCourse] = useState({
    code: "",
    name: "",
    subject: "",
    session: "",
  });
  useEffect(() => {
    const user = JSON.parse(localStorage.getItem("user"));
    if (user) {
      if (user.isLoggedIn === undefined || user.isLoggedIn === false) {
        router.push("/auth");
      }
      if (user.role === "teacher") {
        setIsTeacher(true);
      }
    } else {
      router.push("/auth");
    }
  }, []);
  useEffect(() => {
    if (id) {
      axios.get(`/api/courses/${id}`).then((res) => {
        setCourse({ ...course, ...res.data.data });
        console.log(res.data);
      });
    }
  }, [id]);

  return (
    <div
      style={{
        minWidth: "100vw",
        minHeight: "100vh",
        backgroundImage:
          "linear-gradient(135deg, rgba(186, 186, 186, 0.03) 0%, rgba(186, 186, 186, 0.03) 10%,rgba(133, 133, 133, 0.03) 10%, rgba(133, 133, 133, 0.03) 14%,rgba(38, 38, 38, 0.03) 14%, rgba(38, 38, 38, 0.03) 17%,rgba(93, 93, 93, 0.03) 17%, rgba(93, 93, 93, 0.03) 25%,rgba(80, 80, 80, 0.03) 25%, rgba(80, 80, 80, 0.03) 45%,rgba(239, 239, 239, 0.03) 45%, rgba(239, 239, 239, 0.03) 100%),linear-gradient(135deg, rgba(236, 236, 236, 0.03) 0%, rgba(236, 236, 236, 0.03) 47%,rgba(182, 182, 182, 0.03) 47%, rgba(182, 182, 182, 0.03) 63%,rgba(223, 223, 223, 0.03) 63%, rgba(223, 223, 223, 0.03) 81%,rgba(86, 86, 86, 0.03) 81%, rgba(86, 86, 86, 0.03) 89%,rgba(23, 23, 23, 0.03) 89%, rgba(23, 23, 23, 0.03) 90%,rgba(226, 226, 226, 0.03) 90%, rgba(226, 226, 226, 0.03) 100%),linear-gradient(45deg, rgba(52, 52, 52, 0.03) 0%, rgba(52, 52, 52, 0.03) 31%,rgba(246, 246, 246, 0.03) 31%, rgba(246, 246, 246, 0.03) 63%,rgba(188, 188, 188, 0.03) 63%, rgba(188, 188, 188, 0.03) 71%,rgba(15, 15, 15, 0.03) 71%, rgba(15, 15, 15, 0.03) 87%,rgba(127, 127, 127, 0.03) 87%, rgba(127, 127, 127, 0.03) 93%,rgba(234, 234, 234, 0.03) 93%, rgba(234, 234, 234, 0.03) 100%),linear-gradient(90deg, #ffffff,#ffffff)",
      }}
    >
      <Head>
        <title>LabTastic</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />

      <div
        style={{
          marginLeft: 200,
          borderRadius: "15px",
          backgroundColor: "rgba(204, 237, 255, 0.4)",
          padding: "20px",
          width: "30%",
        }}
      >
        <Text size="xl">{course.name}</Text>
        <Text size="lg">{course.subject}</Text>
        <Text size="md">{course.session}</Text>
      </div>
      <div style={{ display: "flex", justifyContent: "space-evenly" }}>
        <div>
          <Button
            variant="gradient"
            gradient={{ from: "indigo", to: "cyan" }}
            onClick={() => {
              setCodeModal(true);
            }}
          >
            Class Code
          </Button>
          <Button
            variant="gradient"
            gradient={{ from: "teal", to: "lime", deg: 105 }}
            sx={{ margin: 20 }}
          >
            Give Task
          </Button>
        </div>
        <Button
          variant="gradient"
          size="xl"
          gradient={{ from: "teal", to: "blue" }}
          onClick={() => {
            setLabDemo(true);
          }}
        >
          Demonstate a lab
        </Button>
        <div>
          <Button variant="gradient" gradient={{ from: "orange", to: "red" }}>
            Students
          </Button>
          <Button
            variant="gradient"
            gradient={{ from: "#ed6ea0", to: "#ec8c69", deg: 35 }}
            sx={{ margin: 20 }}
          >
            Evaluations
          </Button>
        </div>
      </div>
      <CodeModal
        opened={codeModal}
        setOpened={setCodeModal}
        code={course.code}
      />
      <LabSelectModal
        opened={labDemo}
        setOpened={setLabDemo}
        subject={course.subject}
      />
    </div>
  );
}

// export async function getServerSideProps(context) {
//   //   const data = await axios.get("http://localhost:3000/api/courses", {
//   //     headers: {
//   //       authToken: `${context.req.cookies.authToken}`,
//   //     },
//   //   });
//   //   console.log(data.data);
//   //   return {
//   //     props: {
//   //       courses: data.data.data,
//   //     },
//   //   };
// }
